export const legacyArticleRedirects: Record<string, string> = {
  "stack-ai-hemat-mahasiswa-2026": "ai-stack-for-students",
  "chatgpt-plus-vs-gratis-2026": "chatgpt-paid-vs-free",
  "sharing-vs-private-chatgpt-plus": "shared-vs-private",
  "panduan-api-key-pemula": "api-key-beginners",
  "aktifkan-gemini-pro-invite-vs-login": "safe-digital-subscriptions",
  "chatgpt-plus-logout-sendiri-solusi": "safe-digital-subscriptions",
  "chatgpt-plus-atau-gemini-pro-2026": "chatgpt-vs-gemini",
  "estimasi-token-api-key": "token-cost-estimation",
  "cara-bayar-qris-akun-premium": "safe-digital-subscriptions",
  "apa-itu-akun-private": "shared-vs-private",
  "gemini-pro-untuk-skripsi": "ai-for-thesis-research",
  "bikin-bot-whatsapp-api-key": "whatsapp-ai-bot",
  "tips-aman-akun-sharing": "shared-vs-private",
  "tips-maksimalkan-chatgpt-plus-untuk-mahasiswa": "ai-stack-for-students",
  "perbandingan-chatgpt-plus-vs-gemini-pro-2025": "chatgpt-vs-gemini",
  "cara-aman-berlangganan-akun-ai-sharing": "shared-vs-private",
  "manfaat-api-key-ai-untuk-developer-pemula": "api-key-beginners",
}
