import { randomBytes } from "node:crypto"
import { existsSync, readFileSync, writeFileSync } from "node:fs"

const envPath = ".env.local"

const placeholders = {
  DATABASE_URL: "postgresql://USER:PASSWORD@HOST-pooler.REGION.aws.neon.tech/DB?sslmode=require",
  DIRECT_URL: "postgresql://USER:PASSWORD@HOST.REGION.aws.neon.tech/DB?sslmode=require",
  APP_URL: "http://localhost:3000",
  AUTH_URL: "http://localhost:3000",
  AUTH_SECRET: "",
  AUTH_GOOGLE_ID: "",
  AUTH_GOOGLE_SECRET: "",
  MIDTRANS_SERVER_KEY: "",
  MIDTRANS_CLIENT_KEY: "",
  MIDTRANS_IS_PRODUCTION: "false",
  CREDENTIAL_ENCRYPTION_KEY: "",
  SEED_ADMIN_EMAIL: "admin@geraiakun.id",
  SEED_ADMIN_PASSWORD: "geraiakun-admin",
}

function secret() {
  return randomBytes(48).toString("base64url")
}

function parseEnv(content) {
  const values = {}
  for (const line of content.split(/\r?\n/)) {
    if (!line || line.trimStart().startsWith("#")) continue
    const separator = line.indexOf("=")
    if (separator === -1) continue
    const key = line.slice(0, separator).trim()
    const rawValue = line.slice(separator + 1).trim()
    values[key] = rawValue.replace(/^"|"$/g, "")
  }
  return values
}

function quote(value) {
  return JSON.stringify(value)
}

const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : {}
const next = { ...placeholders, ...existing }

if (!next.AUTH_SECRET || next.AUTH_SECRET.includes("replace-with")) {
  next.AUTH_SECRET = secret()
}

if (!next.CREDENTIAL_ENCRYPTION_KEY || next.CREDENTIAL_ENCRYPTION_KEY.includes("replace-with")) {
  next.CREDENTIAL_ENCRYPTION_KEY = secret()
}

const lines = [
  "# Generated by pnpm setup:env",
  "# Fill DATABASE_URL, DIRECT_URL, Google, Midtrans, and email provider values from their dashboards.",
  "",
  "# Database",
  `DATABASE_URL=${quote(next.DATABASE_URL)}`,
  `DIRECT_URL=${quote(next.DIRECT_URL)}`,
  "",
  "# App/Auth",
  `APP_URL=${quote(next.APP_URL)}`,
  `AUTH_URL=${quote(next.AUTH_URL)}`,
  `AUTH_SECRET=${quote(next.AUTH_SECRET)}`,
  `AUTH_GOOGLE_ID=${quote(next.AUTH_GOOGLE_ID)}`,
  `AUTH_GOOGLE_SECRET=${quote(next.AUTH_GOOGLE_SECRET)}`,
  "",
  "# Midtrans Sandbox",
  `MIDTRANS_SERVER_KEY=${quote(next.MIDTRANS_SERVER_KEY)}`,
  `MIDTRANS_CLIENT_KEY=${quote(next.MIDTRANS_CLIENT_KEY)}`,
  `MIDTRANS_IS_PRODUCTION=${quote(next.MIDTRANS_IS_PRODUCTION)}`,
  "",
  "# Credential vault encryption",
  `CREDENTIAL_ENCRYPTION_KEY=${quote(next.CREDENTIAL_ENCRYPTION_KEY)}`,
  "",
  "# Optional seed admin",
  `SEED_ADMIN_EMAIL=${quote(next.SEED_ADMIN_EMAIL)}`,
  `SEED_ADMIN_PASSWORD=${quote(next.SEED_ADMIN_PASSWORD)}`,
  "",
]

writeFileSync(envPath, `${lines.join("\n")}\n`, "utf8")
console.log(`${envPath} is ready. Replace placeholder service values before running DB migration.`)
